apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-express-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-exp
  template:
    metadata:
      labels:
        app: mongo-exp
    spec:
      containers:
      - name: docker-mongo-express
        image: mongo-express
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
        ports:
        - containerPort: 8081
        env: #mongo-express works with basic mongo image without the need to specify credentials
        #  - name: ME_CONFIG_MONGODB_ADMINUSERNAME
        #    value: ''
        #  - name: ME_CONFIG_MONGODB_ADMINPASSWORD
        #    value: ''
          - name: ME_CONFIG_MONGODB_SERVER
            value: mongodb     # this is name of the service through which mongo db is accessible    
          - name: ME_CONFIG_MONGODB_PORT
            value: '27017'   
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-exp-svc
spec:
  selector:
    app: mongo-exp
  type: LoadBalancer #this type denotes that this is External Service, together with the nodePort below
  ports:
    - protocol: TCP
      port: 8082        #port that service is accessable within the internal node/namespace/network
      targetPort: 8081  #needs to match container port
      nodePort: 30082   #external port that the node can be accessed through via browser etc
