apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-db
  template:
    metadata:
      labels:
        app: mongo-db
    spec:
      containers:
      - name: docker-mongo
        image: mongo
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
        ports:
        - containerPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb #this is the name accessible within the node, similar to 'hostname' in docker-compose
spec:
  selector:
    app: mongo-db
  ports:
    - protocol: TCP
      port: 27017 #this is the port that service [in fact mongo db] will be accessible through
      targetPort: 27017 #this needs to match the container/pod port from section above
