apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper-app
  template:
    metadata:
      labels:
        app: zookeeper-app
    spec:
      containers:
      - env:
        - name: ZOOKEEPER_CLIENT_PORT
          value: "2181"
        - name: ZOOKEEPER_TICK_TIME
          value: "2000"
        image: confluentinc/cp-zookeeper:latest
        imagePullPolicy: IfNotPresent
        name: zookeeper-app
        ports:
        - containerPort: 2181
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper #this is the name accessible within the node, similar to 'hostname' in docker-compose. referenced in kafka-deploy.yaml
spec:
  selector:
    app: zookeeper-app
  type: NodePort
  ports:
    - protocol: TCP
      port: 2181 #this is the static port that service will be accessible through
      nodePort: 30181 #this is the port that will be opened on all pods currently running the 'selector:app'. not secure
      targetPort: 2181 #this needs to match the container/pod port from section above